driver: correct "dri2.h" include path
We don't have a dri2.h locally, it belongs to xorg. Depending on a building
environment, compilation may fail due to a non-existent local include of dri2.h.

In file included from /tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999/src/dri2.c:1:0:
/tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999/src/driver.h:96:18: fatal error: dri2.h: No such file or directory
In file included from /tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999/src/common_helpers.c:23:0:
/tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999/src/driver.h:96:18: fatal error: dri2.h: No such file or directory
In file included from /tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999/src/driver.c:32:0:
/tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999/src/driver.h:96:18: fatal error: dri2.h: No such file or directory
compilation terminated.
compilation terminated.
compilation terminated.
make[2]: *** [Makefile:513: dri2.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:513: common_helpers.lo] Error 1
make[2]: *** [Makefile:513: driver.lo] Error 1
make[2]: Leaving directory '/tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999_build/src'
make[1]: *** [Makefile:502: all-recursive] Error 1
make[1]: Leaving directory '/tmp/portage/x11-drivers/xf86-video-opentegra-9999/work/xf86-video-opentegra-9999_build'
make: *** [Makefile:413: all] Error 2